version: '3.9'
services:
  vuttr-db:
    image: neo4j:4.4-enterprise
    container_name: vuttr-db
    restart: always
    build:
      context: ./vuttr-database
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./.docker/neo4j/data:/data
      - ./.docker/neo4j/logs:/logs
      - ./.docker/neo4j/import:/var/lib/neo4j/import
      - ./.docker/neo4j/plugins:/plugins
      - ./vuttr-database/initial-data.cql:/cyphers/initial-data.cql
    environment:
      - NEO4J_AUTH=none
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes

