spring:
  application:
    name: vuttr-service
  neo4j:
    uri: neo4j://${NEO4J_HOST:localhost}:${NEO4J_PORT:7687}
    authentication:
      username: ${NEO4J_USER:neo4j}
      password: ${NEO4J_PASS:12345678}
  devtools:
    livereload:
      enabled: true
server:
  servlet:
    context-path: /api/vuttr-service
  address: 0.0.0.0
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    show-extensions: true
    show-common-extensions: true
